version: "3.8"


networks:
  website:
    name: website

services:
  next:
    image: eu.gcr.io/dle-dev/frontend:latest
    container_name: dle-next
    ports:
      - "3000:3000"
    networks:
      - website
    depends_on:
      - strapi
  strapi:
    image: eu.gcr.io/dle-dev/backend:latest
    container_name: dle-strapi
    ports:
      - "1337:1337"
    networks:
      - website
    depends_on:
      - db
  db:
    image: eu.gcr.io/dle-dev/backend-db:latest
    container_name: strapi-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD="${STRAPI_POSTGRES_PASSWORD}"
