name: Deploy Production

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to deploy
        required: true
        type: string

permissions:
  contents: read
  deployments: write

jobs:
  publish-web-app:
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.deployment-url }}
    name: Deploy Webapp
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/env-setup
        with:
          node-version: 24.14.1
          pnpm-version: 10.33.0
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.ref || github.ref }}

      - env:
          IS_CI: false
        name: Build
        run: |
          pnpm run build

      - name: Publish Web App
        id: deploy
        uses: ./.github/actions/pages-deploy
        with:
          account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          branch: master
          project-name: dle-dev
