# This is a basic workflow to automatically build a Svelte app and deploy it to GitHub Pages

jobs:
  install-dependencies:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.title == 'Version packages' }}
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: ./.github/actions/env-setup
        with:
          node-version: 24.14.1
          pnpm-version: 10.33.0
          ref: ${{ github.event.pull_request.merge_commit_sha }}

  publish-web-app:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.title == 'Version packages' }}
    environment: dle-dev (Production)
    name: Deploy Webapp
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: ./.github/actions/env-setup
        with:
          node-version: 24.14.1
          pnpm-version: 10.33.0
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Build
        run: |
          pnpm run build
      - name: Publish Web App
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          branch: master
          directory: ./.svelte-kit/cloudflare
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: dle-dev

name: Publish to Production

on:
  pull_request:
    types:
      - closed
    branches:
      - master
